language: go
go:
- 1.4
- 1.5
- 1.6
- master

install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script:
    - go get -t -v ./...
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: F/aaF4vFfKzvasW3Unezzrj6hfUSJzzCCvNHm77YFPIHsde9yJCogDc3RozA4/iSMz9fIh1ctS5BjRU8oZDiIoDWnfYD6pLzE8wuA828u1ZsENkLiFJ4PppgH7kHeuNVn+mR6Cxt5y/v3f0xr9VtyDEX7udrkdPXHbRVSIX4u7uwQNjBk50YH4jC3R9W6if8m5Op2jyUPNn9aQErR4m6acS62yiNa/Tz2ZDczNv+jyiBrLvXs5Xhtrc/lTq1seE0ZUEb6P+5cf7F+vxKWyI9bAVFdOhtbmWGY2fVqVc8Sib21jBitCtY5YiDq7tel78Xz8tKJkKf1zSdxheKdiNdtSPjikAk9I+JVN1bBblKaoIdAgpmJa6ODuNsbLblKCNKVxYSvOQZBZLD5H+vmWJUHQ0VxUp1b3jUgkzRJGI56Q/h8RisoxTFWiqPMF2MlnUiGt8KAQnMB5OqjexkxYxFWCnz1jFRCGJbBkSGsXiEvNY+0Bfk4tzBL5b2bxmL0BIveLd5OthgKQNSbexvX+isXXHFPz3bPKsjKtvKBgvMpkH9/RAYgaqLHJKtGLqgcGKe4xeVCjZPUWcwLlhXmaFyaWJtV7Q/nWjjtTNAo8c6SOvFiSOWV901d+0hDiJxJ+uVSnyHXXKUa7tr22EADxQG4WtMHpozYCCIHcFA69pIr8U=
